CREATE TABLE CARGO (
	Id_cargo INT NOT NULL PRIMARY KEY,
	nombre VARCHAR(100) NOT NULL,
	descripcion VARCHAR(200) NOT NULL
);

CREATE TABLE EMPLEADO (
	Id_empleado CHAR(20) NOT NULL PRIMARY KEY,
	nombre CHAR(20) NOT NULL,
	apaterno CHAR(20) NOT NULL,
	amaterno CHAR(20) NULL,
  	sexo CHAR(1) NOT NULL,
	C_Id_cargo INT NULL,
  	FOREIGN KEY(C_Id_cargo) REFERENCES CARGO(Id_cargo)
);

CREATE TABLE HISTORICO (
	E_Id_empleado CHAR(20) NOT NULL,
	fecha DATE NOT NULL,
	hora TIME  NOT NULL,
	tipo CHAR(10) NOT NULL
);